### ISSUE TITLE
Исправить

### ISSUE THREAD

**Issue by pridybailo-n** [nikitatsvirko/Best-Exchange-Rates#2]
Обработка исключений
Названия переменных

**Comment by nikitatsvirko** [comment]
В названиях переменных проблем не увидел, только дефолтные есть.
Исключения везде где надо есть.

**Comment by trtpo** [comment]
Просьба не ревьюрировать замечания ревьюера - он ревьюирует как может :)

Меня вот это смутило 
 String[] data = {
                "Mon 6/23 - Sunny - 31/17",
                "Tue 6/24 - Foggy - 21/8",
                "Wed 6/25 - Cloudy - 22/17",
                "Thurs 6/26 - Rainy - 18/11",
                "Fri 6/27 - Foggy - 21/10",
                "Sat 6/28 - TRAPPED IN WEATHERSTATION - 23/18",
                "Sun 6/29 - Sunny - 20/7"
        };
